### ISSUE TITLE
Searching for things using arguments

### ISSUE THREAD

**Issue by ddofborg** [jjkester/moneybird-python#3]
Are you sure your .get() methods works?

This line:

`moneybird.get('sales_invoices?filter=contact_id:%s' % contact['id'], administration_id=id)`

creates the following URL in _get_url():

`https://moneybird.com/api/v2/123/sales_invoices?filter=contact_id:456.json`

It seems the parameters are not processed. It should be I would think:

`https://moneybird.com/api/v2/123/sales_invoices.json?filter=contact_id:456`

**Comment by remcotjeerdsma** [comment]
Experiencing the same issue. _get_url() could be extended with an extra argument for queries that is prepended after json to fix this.

I added a 'queries' attribute and added following lines just before the return:
`if queries is not None:
            url = urljoin(url, '?%s' % queries)
`
